### ISSUE TITLE
Add a scroll-to-top button

### ISSUE THREAD

**Issue by Sriansh-raj** [Sriansh-raj/Personal-Portfolio#1]
Can you just add a scroll to top button ??

hehe <3

**Comment by Osiris34** [comment]
Hey can you assign this issue to me I would like to complete this issue?

**Comment by shyamtawli** [comment]
Hey i can complete this issue , assign me if you want.

**Comment by Sriansh-raj** [comment]
> Hey can you assign this issue to me I would like to complete this issue?

Thanks Buddy 😁

**Comment by shyamtawli** [comment]
Ohh i am late. my bad

**Comment by Sriansh-raj** [comment]
> Ohh i am late. my bad

It's okay. <3
